<a href="https://colab.research.google.com/github/2303A51756/2303A51756_B11_PDS/blob/main/pdslab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Step 1: Create a 2D NumPy array for student marks in 3 subjects (5 students)
# Format: Rows = Students, Columns = Subjects
marks = np.array([
    [85, 78, 92],
    [56, 64, 70],
    [90, 88, 94],
    [72, 60, 65],
    [88, 82, 91]
])
print("Student Marks Array:\n", marks)

Student Marks Array:
 [[85 78 92]
 [56 64 70]
 [90 88 94]
 [72 60 65]
 [88 82 91]]


In [ ]:
# Step 2: Calculate average, minimum, and maximum marks for each student
average_marks = np.mean(marks, axis=1)
min_marks = np.min(marks, axis=1)
max_marks = np.max(marks, axis=1)

print("\nAverage Marks per Student:", average_marks)
print("Minimum Marks per Student:", min_marks)
print("Maximum Marks per Student:", max_marks)


Average Marks per Student: [85.         63.33333333 90.66666667 65.66666667 87.        ]
Minimum Marks per Student: [78 56 88 60 82]
Maximum Marks per Student: [92 70 94 72 91]


In [ ]:
# Step 3: Use slicing to retrieve marks of specific students (e.g., 1st and 3rd students)
print("\nMarks of 1st and 3rd students:\n", marks[[0, 2]])



Marks of 1st and 3rd students:
 [[85 78 92]
 [90 88 94]]


In [ ]:
# Step 4: Use boolean indexing to find students scoring above 80 in any subject
# Create a boolean array
above_80 = marks > 80
print("\nBoolean array of marks > 80:\n", above_80)

# Find student indices where any subject has a mark > 80
students_above_80 = np.any(marks > 80, axis=1)
print("\nStudents scoring above 80 in any subject:\n", marks[students_above_80])



Boolean array of marks > 80:
 [[ True False  True]
 [False False False]
 [ True  True  True]
 [False False False]
 [ True  True  True]]

Students scoring above 80 in any subject:
 [[85 78 92]
 [90 88 94]
 [88 82 91]]


In [ ]:
# Step 5: Reshape the array to observe subject-wise performance
# Transpose the array to make columns = students, rows = subjects
subject_wise = marks.T
print("\nSubject-wise Marks (Rows = Subjects):\n", subject_wise)

# Step 6: Analysis/Observations
# Print average score per subject
avg_subject_marks = np.mean(subject_wise, axis=1)
print("\nAverage Marks per Subject:", avg_subject_marks)


Subject-wise Marks (Rows = Subjects):
 [[85 56 90 72 88]
 [78 64 88 60 82]
 [92 70 94 65 91]]

Average Marks per Subject: [78.2 74.4 82.4]


In [ ]:
import numpy as np

# Step 1: Create a 2D NumPy array for student marks in 3 subjects (5 students)
# Format: Rows = Students, Columns = Subjects
marks = np.array([
    [85, 78, 92],
    [56, 64, 70],
    [90, 88, 94],
    [72, 60, 65],
    [88, 82, 91]
])
print("Student Marks Array:\n", marks)

# Step 2: Calculate average, minimum, and maximum marks for each student
average_marks = np.mean(marks, axis=1)
min_marks = np.min(marks, axis=1)
max_marks = np.max(marks, axis=1)

print("\nAverage Marks per Student:", average_marks)
print("Minimum Marks per Student:", min_marks)
print("Maximum Marks per Student:", max_marks)

# Step 3: Use slicing to retrieve marks of specific students (e.g., 1st and 3rd students)
print("\nMarks of 1st and 3rd students:\n", marks[[0, 2]])

# Step 4: Use boolean indexing to find students scoring above 80 in any subject
# Create a boolean array
above_80 = marks > 80
print("\nBoolean array of marks > 80:\n", above_80)

# Find student indices where any subject has a mark > 80
students_above_80 = np.any(marks > 80, axis=1)
print("\nStudents scoring above 80 in any subject:\n", marks[students_above_80])

# Step 5: Reshape the array to observe subject-wise performance
# Transpose the array to make columns = students, rows = subjects
subject_wise = marks.T
print("\nSubject-wise Marks (Rows = Subjects):\n", subject_wise)

# Step 6: Analysis/Observations
# Print average score per subject
avg_subject_marks = np.mean(subject_wise, axis=1)
print("\nAverage Marks per Subject:", avg_subject_marks)


Student Marks Array:
 [[85 78 92]
 [56 64 70]
 [90 88 94]
 [72 60 65]
 [88 82 91]]

Average Marks per Student: [85.         63.33333333 90.66666667 65.66666667 87.        ]
Minimum Marks per Student: [78 56 88 60 82]
Maximum Marks per Student: [92 70 94 72 91]

Marks of 1st and 3rd students:
 [[85 78 92]
 [90 88 94]]

Boolean array of marks > 80:
 [[ True False  True]
 [False False False]
 [ True  True  True]
 [False False False]
 [ True  True  True]]

Students scoring above 80 in any subject:
 [[85 78 92]
 [90 88 94]
 [88 82 91]]

Subject-wise Marks (Rows = Subjects):
 [[85 56 90 72 88]
 [78 64 88 60 82]
 [92 70 94 65 91]]

Average Marks per Subject: [78.2 74.4 82.4]


In [ ]:
import pandas as pd

# Step 1: Create a dictionary with employee details
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'ID': [101, 102, 103, 104, 105],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'HR'],
    'Salary': [48000, 52000, 61000, 45000, 75000]
}

# Step 2: Create a DataFrame
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Step 3: Filter employees with salary > 50,000
high_salary_df = df[df['Salary'] > 50000]
print("\nEmployees with Salary > 50,000:\n", high_salary_df)

# Step 4: Sort the DataFrame by salary in descending order
sorted_df = df.sort_values(by='Salary', ascending=False)
print("\nDataFrame Sorted by Salary (Descending):\n", sorted_df)

# Step 5: Add a new column for Bonus (10% of salary)
df['Bonus'] = df['Salary'] * 0.10
print("\nDataFrame with Bonus Column:\n", df)

# Step 6: Calculate total salary expense including bonuses
df['TotalPay'] = df['Salary'] + df['Bonus']
total_expense = df['TotalPay'].sum()
print("\nTotal Salary Expense (including Bonuses): ₹", total_expense)

# Step 7: Save the updated DataFrame to CSV
df.to_csv("employee_salary_analysis.csv", index=False)
print("\nCSV file 'employee_salary_analysis.csv' has been saved.")


Original DataFrame:
       Name   ID Department  Salary
0    Alice  101         HR   48000
1      Bob  102         IT   52000
2  Charlie  103    Finance   61000
3    David  104         IT   45000
4      Eva  105         HR   75000

Employees with Salary > 50,000:
       Name   ID Department  Salary
1      Bob  102         IT   52000
2  Charlie  103    Finance   61000
4      Eva  105         HR   75000

DataFrame Sorted by Salary (Descending):
       Name   ID Department  Salary
4      Eva  105         HR   75000
2  Charlie  103    Finance   61000
1      Bob  102         IT   52000
0    Alice  101         HR   48000
3    David  104         IT   45000

DataFrame with Bonus Column:
       Name   ID Department  Salary   Bonus
0    Alice  101         HR   48000  4800.0
1      Bob  102         IT   52000  5200.0
2  Charlie  103    Finance   61000  6100.0
3    David  104         IT   45000  4500.0
4      Eva  105         HR   75000  7500.0

Total Salary Expense (including Bonuses): ₹ 309100.0